language: php

matrix:
    include:
        - php: '5.6'
        - php: '7.0'

before_install:
    - if [[ $TRAVIS_PHP_VERSION = '5.6' ]] ; then echo yes | pecl install apcu-4.0.10; fi;

before_script:
    - composer install

script:
    - bin/phpspec run
    - bin/phpunit

notifications:
    email:
        - franiglesias@mac.com
